# Site settings
title: Paz Bakery
email: pazbakery.ca@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://happy-bose-84d3b9.netlify.com/" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
